version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d products -t 5" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - "5432:5432"