# This OTEL collector configuration file that receives data from OTEL SDKs and forwards it to Grafana Agent.

# Receivers' configuration section
# See for more details the following documentation: https://opentelemetry.io/docs/collector/configuration/#receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

# Exporters' configuration section
# See for more details the following documentation: https://opentelemetry.io/docs/collector/configuration/#exporters
exporters:
  otlphttp/grafana-agent:
    endpoint: http://grafana-agent:4318

# Services configuration section
# See for more details the following documentation: https://opentelemetry.io/docs/collector/configuration/#services
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/grafana-agent]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/grafana-agent]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/grafana-agent]
